# Generated by Django 2.0.4 on 2018-07-26 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Genesis', 'Genesis'), ('Exodus', 'Exodus'), ('Leviticus', 'Leviticus'), ('Numbers', 'Numbers'), ('Deuteronomy', 'Deuteronomy'), ('Joshua', 'Joshua'), ('Judges', 'Judges'), ('Ruth', 'Ruth'), ('1 Samuel', '1 Samuel'), ('2 Samuel', '2 Samuel'), ('1 Kings', '1 Kings'), ('2 Kings', '2 Kings'), ('1 Chronicles', '1 Chronicles'), ('2 Chronicles', '2 Chronicles'), ('Ezra', 'Ezra'), ('Nehemiah', 'Nehemiah'), ('Esther', 'Esther'), ('Job', 'Job'), ('Psalms', 'Psalms'), ('Proverbs', 'Proverbs'), ('Ecclesiastes', 'Ecclesiastes'), ('Song of Solomon', 'Song of Solomon'), ('Isaiah', 'Isaiah'), ('Jeremiah', 'Jeremiah'), ('Lamentations', 'Lamentations'), ('Ezekiel', 'Ezekiel'), ('Daniel', 'Daniel'), ('Hosea', 'Hosea'), ('Joel', 'Joel'), ('Amos', 'Amos'), ('Obadiah', 'Obadiah'), ('Jonah', 'Jonah'), ('Micah', 'Micah'), ('Nahum', 'Nahum'), ('Habakkuk', 'Habakkuk'), ('Zephaniah', 'Zephaniah'), ('Haggai', 'Haggai'), ('Zechariah', 'Zechariah'), ('Malachi', 'Malachi'), ('Matthew', 'Matthew'), ('Mark', 'Mark'), ('Luke', 'Luke'), ('John', 'John'), ('Acts', 'Acts'), ('Romans', 'Romans'), ('1 Corinthians', '1 Corinthians'), ('2 Corinthians', '2 Corinthians'), ('Galatians', 'Galatians'), ('Ephesians', 'Ephesians'), ('Philippians', 'Philippians'), ('Colossians', 'Colossians'), ('1 Thessalonians', '1 Thessalonians'), ('2 Thessalonians', '2 Thessalonians'), ('1 Timothy', '1 Timothy'), ('2 Timothy', '2 Timothy'), ('Titus', 'Titus'), ('Philemon', 'Philemon'), ('Hebrews', 'Hebrews'), ('James', 'James'), ('1 Peter', '1 Peter'), ('2 Peter', '2 Peter'), ('1 John', '1 John'), ('2 John', '2 John'), ('3 John', '3 John'), ('Jude', 'Jude'), ('Revelation', 'Revelation'), ('창세기', '창세기'), ('출애굽기', '출애굽기'), ('레위기', '레위기'), ('민수기', '민수기'), ('신명기', '신명기'), ('여호수아', '여호수아'), ('재판관기', '재판관기'), ('룻기', '룻기'), ('사무엘상', '사무엘상'), ('사무엘하', '사무엘하'), ('열왕기상', '열왕기상'), ('열왕기하', '열왕기하'), ('역대기상', '역대기상'), ('역대기하', '역대기하'), ('에스라', '에스라'), ('느헤미야', '느헤미야'), ('에스더', '에스더'), ('욥기', '욥기'), ('시편', '시편'), ('잠언', '잠언'), ('전도서', '전도서'), ('솔로몬의 노래', '솔로몬의 노래'), ('이사야', '이사야'), ('예레미야', '예레미야'), ('예레미야 애가', '예레미야 애가'), ('에스겔', '에스겔'), ('다니엘', '다니엘'), ('호세아', '호세아'), ('요엘', '요엘'), ('아모스', '아모스'), ('오바댜', '오바댜'), ('요나', '요나'), ('미카', '미카'), ('나훔', '나훔'), ('하박국', '하박국'), ('스파냐', '스파냐'), ('학개', '학개'), ('스카랴', '스카랴'), ('말라키', '말라키'), ('마태복음', '마태복음'), ('마가복음', '마가복음'), ('누가복음', '누가복음'), ('요한복음', '요한복음'), ('사도행전', '사도행전'), ('로마서', '로마서'), ('고린도전서', '고린도전서'), ('고린도후서', '고린도후서'), ('갈라디아서', '갈라디아서'), ('에베소서', '에베소서'), ('빌립보서', '빌립보서'), ('골로새서', '골로새서'), ('데살로니가전서', '데살로니가전서'), ('데살로니가후서', '데살로니가후서'), ('디모데전서', '디모데전서'), ('디모데후서', '디모데후서'), ('디도서', '디도서'), ('빌레몬서', '빌레몬서'), ('히브리서', '히브리서'), ('야고보서', '야고보서'), ('베드로전서', '베드로전서'), ('베드로후서', '베드로후서'), ('요한일서', '요한일서'), ('요한이서', '요한이서'), ('요한삼서', '요한삼서'), ('유다서', '유다서'), ('요한계시록', '요한계시록')], max_length=15)),
                ('name_en', models.CharField(max_length=15)),
                ('is_old', models.BooleanField()),
                ('lang', models.CharField(choices=[('kr', 'Korean'), ('en', 'English')], max_length=2)),
                ('version', models.CharField(choices=[('KJV', 'King James Version'), ('HKJV', '한글 킹제임스'), ('HJV', '흠정역')], max_length=4)),
                ('number_of_chapters', models.IntegerField(default=0)),
                ('number_of_verses', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('number_of_verses', models.IntegerField(default=0)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='scripture.Book')),
            ],
        ),
        migrations.CreateModel(
            name='Verse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(choices=[('KJV', 'King James Version'), ('HKJV', '한글 킹제임스'), ('HJV', '흠정역')], max_length=4)),
                ('book_name', models.CharField(max_length=20)),
                ('book_name_abbr', models.CharField(max_length=10)),
                ('book_name_en', models.CharField(max_length=20)),
                ('chapter_number', models.CharField(max_length=3)),
                ('number', models.IntegerField()),
                ('content', models.TextField()),
                ('loc', models.CharField(max_length=30)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verses', to='scripture.Book')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verses', to='scripture.Chapter')),
            ],
        ),
    ]
