# Generated by Django 2.0.4 on 2018-07-27 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scripture', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scripture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(choices=[('KJV', 'King James Version'), ('HKJV', '한글 킹제임스'), ('HJV', '흠정역')], max_length=4)),
                ('lang', models.CharField(choices=[('kr', 'Korean'), ('en', 'English')], max_length=2)),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='scripture',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='scripture.Scripture', verbose_name='books'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chapter',
            name='scripture',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='scripture.Scripture', verbose_name='chapters'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='verse',
            name='scripture',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='scripture.Scripture', verbose_name='chapters'),
            preserve_default=False,
        ),
    ]
