# Generated by Django 2.0.4 on 2018-07-27 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scripture', '0002_auto_20180727_0516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='scripture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='scripture.Scripture'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='scripture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='scripture.Scripture'),
        ),
        migrations.AlterField(
            model_name='verse',
            name='scripture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verses', to='scripture.Scripture'),
        ),
    ]
